stages:
  - test
  - deploy

test:
  stage: test
  image: node:16.17.1-alpine3.15
  before_script:
    - apk --no-cache add curl
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm lint
    - vue-tsc --noEmit
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

deploy:prd:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Deploying production"
    - curl --fail-with-body -s "https://api.render.com/deploy/srv-${RENDER_SRV_ID}?key=${RENDER_DEPLOY_KEY}" -o file.txt >/dev/null 2>&1
  environment:
    name: Production
    url: https://admissions-frontend-prd.onrender.com
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:staging:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Deploying staging"
    - curl --fail-with-body -s "https://api.render.com/deploy/srv-${RENDER_SRV_ID}?key=${RENDER_DEPLOY_KEY}" -o file.txt >/dev/null 2>&1
  environment:
    name: Staging
    url: https://admissions-frontend-staging.onrender.com
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
