stages:
  - test
  - deploy

test:
  stage: test
  image: node:16.17.1-alpine3.15
  before_script:
    - apk --no-cache add curl
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm lint
    - pnpm vue-tsc --noEmit
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      
.vercel:
  stage: deploy
  image: node:16.16.0
  before_script:
    - npm install --global vercel

deploy for preview:
  extends: .vercel
  except:
    - develop
    - main
  script:
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy to staging:
  extends: .vercel
  only:
    - develop
  script:
    - vercel pull --yes --environment=development --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
  environment:
    name: Staging
    url: https://admissions-frontend-staging.birkhoff.me

deploy to production:
  extends: .vercel
  only:
    - main
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
  environment:
    name: Production
    url: https://admissions.birkhoff.me
