stages:
  - dependencies
  - test
  - deploy

image: node:16

before_script:
  - npm install --location=global pnpm@7
  - pnpm config set store-dir .pnpm-store

default:
  cache: &cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - ./node_modules
    policy: pull

install dependencies:
  stage: dependencies
  interruptible: true
  when: always
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install

test:
  stage: test
  interruptible: true
  script:
    - pnpm lint
    - pnpm vue-tsc --noEmit
    - pnpm test

.vercel:
  stage: deploy
  before_script:
    - npm install --location=global pnpm@7 vercel
    - pnpm config set store-dir .pnpm-store

# mainly for pentest image
build image for pentest:
  image: docker:20.10.21-cli
  stage: build
  only:
    - develop
  services:
    - name: docker:20.10.21-dind
      alias: docker
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username
      $CI_REGISTRY_USER --password-stdin
    - docker run --privileged --rm tonistiigi/binfmt --install all
  variables:
    # This instructs Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
  script:
    - VITE_IS_SKIP_CAPTCHA=true VITE_ADMISSIONS_API_ENDPOINT=https://admissions-backend-pentest.birkhoff.me pnpm build
    - docker buildx create --use
    - docker buildx build
      --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:pentest-build-cache
      --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:pentest-build-cache,mode=max
      --platform linux/arm64/v8,linux/amd64
      --file "${CI_PROJECT_DIR}/Dockerfile"
      --tag "${CI_REGISTRY_IMAGE}:pentest"
      --tag "${CI_REGISTRY_IMAGE}:pentest-${CI_COMMIT_SHORT_SHA}"
      --push
      "${CI_PROJECT_DIR}"

deploy for review:
  extends: .vercel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' # deploy for review for every MR.
  script:
    - vercel pull --yes --environment=development --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - export DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
    - echo "DYNAMIC_ENVIRONMENT_URL=$DEPLOYMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL

deploy to staging:
  extends: .vercel
  only:
    - develop
  script:
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - export DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
    - timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' '"$DEPLOYMENT_URL"')" != "200" ]]; do sleep 5; done' || false
    - vercel alias set -d --token="$VERCEL_TOKEN" --scope "ntnu-csie-admissions" "$DEPLOYMENT_URL" "admissions-frontend-staging.birkhoff.me"
  environment:
    name: Staging
    url: https://admissions-frontend-staging.birkhoff.me

deploy to production:
  extends: .vercel
  only:
    - main
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - export DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
    - timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' '"$DEPLOYMENT_URL"')" != "200" ]]; do sleep 5; done' || false
    - vercel alias set -d --token="$VERCEL_TOKEN" --scope "ntnu-csie-admissions" "$DEPLOYMENT_URL" "admissions.birkhoff.me"
  environment:
    name: Production
    url: https://admissions.birkhoff.me

deploy to pentest:
  stage: deploy
  tags:
    - deploy
  # only:
  #   - develop
  variables:
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  before_script:
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
  script:
    - ansible-galaxy collection install community.docker
    - DOCKER_IMAGE="${CI_REGISTRY_IMAGE}:pentest-${CI_COMMIT_SHORT_SHA}"
      ansible-playbook --connection=local --inventory=127.0.0.1, playbook-pentest.yml
  environment:
    name: pentest
    url: https://admissions-frontend-pentest.birkhoff.me
