// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ForgetPasswordForm: typeof import('./src/components/ForgetPasswordForm.vue')['default']
    LandingViewLayout: typeof import('./src/components/LandingViewLayout.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PasswordRecoveryEmailSent: typeof import('./src/components/PasswordRecoveryEmailSent.vue')['default']
    ResetPasswordForm: typeof import('./src/components/ResetPasswordForm.vue')['default']
    ReviewerSidebar: typeof import('./src/components/ReviewerSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Turnstile: typeof import('./src/components/Turnstile.vue')['default']
  }
}
