---
- name: Deploy admissions-frontend-pentest
  hosts: all
  become: true
  gather_facts: false

  vars:
    DOCKER_IMAGE: "{{ lookup('env', 'DOCKER_IMAGE') }}"
    DOMAIN: "admissions-frontend-pentest.birkhoff.me"
    TRAEFIK_INTERNAL_NAME: admissions-frontend-pentest

  tasks:
    - name: File Synchronisation
      ansible.posix.synchronize:
        src: ./
        dest: /srv/admissions-frontend-pentest
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.vscode"
          - "--exclude=logs/*"

    - name: Ensure traefik network
      community.general.docker_network:
        name: traefik
        state: present

    - name: Login to GitLab Container Registry (force re-auth)
      docker_login:
        registry: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY') }}"
        username: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_PASSWORD') }}"
        reauthorize: yes

    - name: Render docker-compose.yml.j2
      template:
        src: docker-compose.yml.j2
        dest: "/srv/admissions-frontend-pentest/docker-compose.yml"

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /srv/admissions-frontend-pentest
        recreate: always
        remove_orphans: yes
      register: output

    - ansible.builtin.debug:
        var: output
